#For local
#DB_URL=jdbc:mysql://localhost:3307/trimlink
#DB_USER=root
#DB_PASSWORD=
#for production
DB_URL=jdbc:mysql://localhost:3306/trimlink
DB_USER=trimlink
DB_PASSWORD=Trim@123
DB_DRIVER=com.mysql.cj.jdbc.Driver
