name: TrimLink CI/CD

on:
  push:
    branches:
        - main

jobs:
  build-and-deploy:
      runs-on: self-hosted
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
      
        - name: Setup Java 25
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '25'
            cache: maven

        - name: Build Project
          run: mvn clean package

        - name: Deploy WAR
          run: |
              sudo cp target/TrimLink-0.0.1-SNAPSHOT.war /var/lib/tomcat10/webapps/trimlink.war
              sudo systemctl restart tomcat10

        - name: Verify Deployment
          run: |
              systemctl status tomcat10 --no-pager

        - name: Runner Information
          run: |
              whoami
              pwd
              hostname
              java -version
              mvn -version
